// Generated by scripts/gen-lucide-icons.mjs — DO NOT EDIT BY HAND.
//
// The Lucide icons this app uses (186 of the 2132 in the bundled
// lucide.ttf), addressed by codepoint. Lucide is the web client's icon library
// (`iconLibrary: "lucide"` in its components.json), so using the same font here
// is what keeps the two clients' glyphs identical rather than merely similar.
//
// Add an icon by listing its name in scripts/sf-to-lucide.json and re-running.

import SwiftUI

/// A Lucide glyph in the bundled icon font.
enum Lucide: String, CaseIterable, Sendable {
    case activity = "activity"
    case archive = "archive"
    case arrowDown = "arrow-down"
    case arrowDownLeft = "arrow-down-left"
    case arrowLeft = "arrow-left"
    case arrowLeftRight = "arrow-left-right"
    case arrowRight = "arrow-right"
    case arrowRightToLine = "arrow-right-to-line"
    case arrowUp = "arrow-up"
    case arrowUpRight = "arrow-up-right"
    case atSign = "at-sign"
    case badgeCheck = "badge-check"
    case bell = "bell"
    case bellRing = "bell-ring"
    case bird = "bird"
    case bot = "bot"
    case braces = "braces"
    case brain = "brain"
    case camera = "camera"
    case chartColumn = "chart-column"
    case check = "check"
    case checkCheck = "check-check"
    case chevronDown = "chevron-down"
    case chevronLeft = "chevron-left"
    case chevronRight = "chevron-right"
    case chevronUp = "chevron-up"
    case chevronsUpDown = "chevrons-up-down"
    case circle = "circle"
    case circleAlert = "circle-alert"
    case circleArrowDown = "circle-arrow-down"
    case circleArrowUp = "circle-arrow-up"
    case circleCheck = "circle-check"
    case circleCheckBig = "circle-check-big"
    case circleDashed = "circle-dashed"
    case circleDot = "circle-dot"
    case circleDotDashed = "circle-dot-dashed"
    case circleHelp = "circle-help"
    case circleMinus = "circle-minus"
    case circlePause = "circle-pause"
    case circlePlay = "circle-play"
    case circlePlus = "circle-plus"
    case circleSlash = "circle-slash"
    case circleStop = "circle-stop"
    case circleUser = "circle-user"
    case circleX = "circle-x"
    case clipboardList = "clipboard-list"
    case clock = "clock"
    case cloud = "cloud"
    case cloudOff = "cloud-off"
    case code = "code"
    case codeXml = "code-xml"
    case cog = "cog"
    case command = "command"
    case copy = "copy"
    case cpu = "cpu"
    case crosshair = "crosshair"
    case database = "database"
    case delete = "delete"
    case download = "download"
    case ellipsis = "ellipsis"
    case ellipsisVertical = "ellipsis-vertical"
    case externalLink = "external-link"
    case eye = "eye"
    case eyeOff = "eye-off"
    case file = "file"
    case fileCode = "file-code"
    case fileDiff = "file-diff"
    case fileOutput = "file-output"
    case filePenLine = "file-pen-line"
    case filePlus = "file-plus"
    case fileText = "file-text"
    case files = "files"
    case filter = "filter"
    case flaskConical = "flask-conical"
    case folder = "folder"
    case folderGit2 = "folder-git-2"
    case folderOpen = "folder-open"
    case folderPlus = "folder-plus"
    case folderSearch = "folder-search"
    case folderTree = "folder-tree"
    case gitBranch = "git-branch"
    case gitCommitHorizontal = "git-commit-horizontal"
    case gitCompare = "git-compare"
    case gitMerge = "git-merge"
    case gitPullRequest = "git-pull-request"
    case globe = "globe"
    case graduationCap = "graduation-cap"
    case gripVertical = "grip-vertical"
    case hardDrive = "hard-drive"
    case hash = "hash"
    case history = "history"
    case hourglass = "hourglass"
    case house = "house"
    case image = "image"
    case images = "images"
    case inbox = "inbox"
    case info = "info"
    case key = "key"
    case keyRound = "key-round"
    case keyboard = "keyboard"
    case keyboardOff = "keyboard-off"
    case languages = "languages"
    case layers = "layers"
    case lightbulb = "lightbulb"
    case list = "list"
    case listChecks = "list-checks"
    case listTodo = "list-todo"
    case listTree = "list-tree"
    case loaderCircle = "loader-circle"
    case lock = "lock"
    case maximize2 = "maximize-2"
    case menu = "menu"
    case messageCircle = "message-circle"
    case messageCircleQuestion = "message-circle-question"
    case messageCircleQuestionMark = "message-circle-question-mark"
    case messageSquare = "message-square"
    case messageSquarePlus = "message-square-plus"
    case messageSquareText = "message-square-text"
    case messagesSquare = "messages-square"
    case monitor = "monitor"
    case moon = "moon"
    case moonStar = "moon-star"
    case network = "network"
    case octagonX = "octagon-x"
    case package = "package"
    case palette = "palette"
    case panelLeft = "panel-left"
    case panelRight = "panel-right"
    case paperclip = "paperclip"
    case pause = "pause"
    case pencil = "pencil"
    case pin = "pin"
    case pinOff = "pin-off"
    case play = "play"
    case plug = "plug"
    case plugZap = "plug-zap"
    case plus = "plus"
    case power = "power"
    case puzzle = "puzzle"
    case qrCode = "qr-code"
    case refreshCw = "refresh-cw"
    case rocket = "rocket"
    case rotateCcw = "rotate-ccw"
    case save = "save"
    case scanQrCode = "scan-qr-code"
    case search = "search"
    case send = "send"
    case sendHorizontal = "send-horizontal"
    case server = "server"
    case settings = "settings"
    case settings2 = "settings-2"
    case shieldAlert = "shield-alert"
    case shieldCheck = "shield-check"
    case sigma = "sigma"
    case slidersHorizontal = "sliders-horizontal"
    case smartphone = "smartphone"
    case sparkles = "sparkles"
    case square = "square"
    case squareCheck = "square-check"
    case squarePen = "square-pen"
    case squareTerminal = "square-terminal"
    case star = "star"
    case stickyNote = "sticky-note"
    case sun = "sun"
    case tag = "tag"
    case terminal = "terminal"
    case timer = "timer"
    case trash2 = "trash-2"
    case trendingUp = "trending-up"
    case triangleAlert = "triangle-alert"
    case type = "type"
    case undo2 = "undo-2"
    case unplug = "unplug"
    case upload = "upload"
    case user = "user"
    case userRound = "user-round"
    case users = "users"
    case videoOff = "video-off"
    case wandSparkles = "wand-sparkles"
    case wifi = "wifi"
    case wifiOff = "wifi-off"
    case workflow = "workflow"
    case wrench = "wrench"
    case x = "x"
    case zap = "zap"
    case zapOff = "zap-off"

    /// The glyph's codepoint in lucide.ttf.
    var codepoint: UInt32 {
        switch self {
        case .activity: return 57400 // U+E038
        case .archive: return 57409 // U+E041
        case .arrowDown: return 57410 // U+E042
        case .arrowDownLeft: return 57411 // U+E043
        case .arrowLeft: return 57416 // U+E048
        case .arrowLeftRight: return 57930 // U+E24A
        case .arrowRight: return 57417 // U+E049
        case .arrowRightToLine: return 58457 // U+E459
        case .arrowUp: return 57418 // U+E04A
        case .arrowUpRight: return 57421 // U+E04D
        case .atSign: return 57422 // U+E04E
        case .badgeCheck: return 57921 // U+E241
        case .bell: return 57433 // U+E059
        case .bellRing: return 57892 // U+E224
        case .bird: return 58309 // U+E3C5
        case .bot: return 57787 // U+E1BB
        case .braces: return 58218 // U+E36A
        case .brain: return 58310 // U+E3C6
        case .camera: return 57444 // U+E064
        case .chartColumn: return 58019 // U+E2A3
        case .check: return 57452 // U+E06C
        case .checkCheck: return 58254 // U+E38E
        case .chevronDown: return 57453 // U+E06D
        case .chevronLeft: return 57454 // U+E06E
        case .chevronRight: return 57455 // U+E06F
        case .chevronUp: return 57456 // U+E070
        case .chevronsUpDown: return 57873 // U+E211
        case .circle: return 57462 // U+E076
        case .circleAlert: return 57463 // U+E077
        case .circleArrowDown: return 57464 // U+E078
        case .circleArrowUp: return 57467 // U+E07B
        case .circleCheck: return 57894 // U+E226
        case .circleCheckBig: return 57468 // U+E07C
        case .circleDashed: return 58544 // U+E4B0
        case .circleDot: return 58181 // U+E345
        case .circleDotDashed: return 58545 // U+E4B1
        case .circleHelp: return 57474 // U+E082
        case .circleMinus: return 57470 // U+E07E
        case .circlePause: return 57471 // U+E07F
        case .circlePlay: return 57472 // U+E080
        case .circlePlus: return 57473 // U+E081
        case .circleSlash: return 58370 // U+E402
        case .circleStop: return 57475 // U+E083
        case .circleUser: return 58465 // U+E461
        case .circleX: return 57476 // U+E084
        case .clipboardList: return 57478 // U+E086
        case .clock: return 57479 // U+E087
        case .cloud: return 57480 // U+E088
        case .cloudOff: return 57485 // U+E08D
        case .code: return 57491 // U+E093
        case .codeXml: return 57862 // U+E206
        case .cog: return 58123 // U+E30B
        case .command: return 57498 // U+E09A
        case .copy: return 57502 // U+E09E
        case .cpu: return 57513 // U+E0A9
        case .crosshair: return 57516 // U+E0AC
        case .database: return 57517 // U+E0AD
        case .delete: return 57518 // U+E0AE
        case .download: return 57522 // U+E0B2
        case .ellipsis: return 57526 // U+E0B6
        case .ellipsisVertical: return 57527 // U+E0B7
        case .externalLink: return 57529 // U+E0B9
        case .eye: return 57530 // U+E0BA
        case .eyeOff: return 57531 // U+E0BB
        case .file: return 57536 // U+E0C0
        case .fileCode: return 57539 // U+E0C3
        case .fileDiff: return 58135 // U+E317
        case .fileOutput: return 57544 // U+E0C8
        case .filePenLine: return 58144 // U+E320
        case .filePlus: return 57545 // U+E0C9
        case .fileText: return 57548 // U+E0CC
        case .files: return 57551 // U+E0CF
        case .filter: return 57564 // U+E0DC
        case .flaskConical: return 57557 // U+E0D5
        case .folder: return 57559 // U+E0D7
        case .folderGit2: return 58378 // U+E40A
        case .folderOpen: return 57927 // U+E247
        case .folderPlus: return 57561 // U+E0D9
        case .folderSearch: return 58169 // U+E339
        case .folderTree: return 58172 // U+E33C
        case .gitBranch: return 57570 // U+E0E2
        case .gitCommitHorizontal: return 57571 // U+E0E3
        case .gitCompare: return 58201 // U+E359
        case .gitMerge: return 57572 // U+E0E4
        case .gitPullRequest: return 57573 // U+E0E5
        case .globe: return 57576 // U+E0E8
        case .graduationCap: return 57908 // U+E234
        case .gripVertical: return 57579 // U+E0EB
        case .hardDrive: return 57581 // U+E0ED
        case .hash: return 57583 // U+E0EF
        case .history: return 57845 // U+E1F5
        case .hourglass: return 58006 // U+E296
        case .house: return 57589 // U+E0F5
        case .image: return 57590 // U+E0F6
        case .images: return 58820 // U+E5C4
        case .inbox: return 57591 // U+E0F7
        case .info: return 57593 // U+E0F9
        case .key: return 57597 // U+E0FD
        case .keyRound: return 58531 // U+E4A3
        case .keyboard: return 57988 // U+E284
        case .keyboardOff: return 58846 // U+E5DE
        case .languages: return 57598 // U+E0FE
        case .layers: return 58665 // U+E529
        case .lightbulb: return 57794 // U+E1C2
        case .list: return 57606 // U+E106
        case .listChecks: return 57808 // U+E1D0
        case .listTodo: return 58563 // U+E4C3
        case .listTree: return 58376 // U+E408
        case .loaderCircle: return 57610 // U+E10A
        case .lock: return 57611 // U+E10B
        case .maximize2: return 57619 // U+E113
        case .menu: return 57621 // U+E115
        case .messageCircle: return 57622 // U+E116
        case .messageCircleQuestion: return 58728 // U+E568
        case .messageCircleQuestionMark: return 58728 // U+E568
        case .messageSquare: return 57623 // U+E117
        case .messageSquarePlus: return 58380 // U+E40C
        case .messageSquareText: return 58741 // U+E575
        case .messagesSquare: return 58381 // U+E40D
        case .monitor: return 57629 // U+E11D
        case .moon: return 57630 // U+E11E
        case .moonStar: return 58384 // U+E410
        case .network: return 57637 // U+E125
        case .octagonX: return 57640 // U+E128
        case .package: return 57641 // U+E129
        case .palette: return 57821 // U+E1DD
        case .panelLeft: return 57642 // U+E12A
        case .panelRight: return 58417 // U+E431
        case .paperclip: return 57645 // U+E12D
        case .pause: return 57646 // U+E12E
        case .pencil: return 57849 // U+E1F9
        case .pin: return 57945 // U+E259
        case .pinOff: return 58038 // U+E2B6
        case .play: return 57660 // U+E13C
        case .plug: return 58239 // U+E37F
        case .plugZap: return 58460 // U+E45C
        case .plus: return 57661 // U+E13D
        case .power: return 57664 // U+E140
        case .puzzle: return 58012 // U+E29C
        case .qrCode: return 57823 // U+E1DF
        case .refreshCw: return 57669 // U+E145
        case .rocket: return 57990 // U+E286
        case .rotateCcw: return 57672 // U+E148
        case .save: return 57677 // U+E14D
        case .scanQrCode: return 58870 // U+E5F6
        case .search: return 57681 // U+E151
        case .send: return 57682 // U+E152
        case .sendHorizontal: return 58610 // U+E4F2
        case .server: return 57683 // U+E153
        case .settings: return 57684 // U+E154
        case .settings2: return 57925 // U+E245
        case .shieldAlert: return 57854 // U+E1FE
        case .shieldCheck: return 57855 // U+E1FF
        case .sigma: return 57857 // U+E201
        case .slidersHorizontal: return 58010 // U+E29A
        case .smartphone: return 57699 // U+E163
        case .sparkles: return 58386 // U+E412
        case .square: return 57703 // U+E167
        case .squareCheck: return 58713 // U+E559
        case .squarePen: return 57714 // U+E172
        case .squareTerminal: return 57866 // U+E20A
        case .star: return 57718 // U+E176
        case .stickyNote: return 58115 // U+E303
        case .sun: return 57720 // U+E178
        case .tag: return 57727 // U+E17F
        case .terminal: return 57729 // U+E181
        case .timer: return 57824 // U+E1E0
        case .trash2: return 57742 // U+E18E
        case .trendingUp: return 57745 // U+E191
        case .triangleAlert: return 57747 // U+E193
        case .type: return 57752 // U+E198
        case .undo2: return 58017 // U+E2A1
        case .unplug: return 58461 // U+E45D
        case .upload: return 57758 // U+E19E
        case .user: return 57759 // U+E19F
        case .userRound: return 58472 // U+E468
        case .users: return 57764 // U+E1A4
        case .videoOff: return 57766 // U+E1A6
        case .wandSparkles: return 58199 // U+E357
        case .wifi: return 57774 // U+E1AE
        case .wifiOff: return 57775 // U+E1AF
        case .workflow: return 58405 // U+E425
        case .wrench: return 57777 // U+E1B1
        case .x: return 57778 // U+E1B2
        case .zap: return 57780 // U+E1B4
        case .zapOff: return 57781 // U+E1B5
        }
    }

    /// The glyph as a one-character string, for `Text`.
    var glyph: String {
        guard let scalar = UnicodeScalar(codepoint) else { return "" }
        return String(Character(scalar))
    }
}

extension Lucide {
    /// The SF Symbol the app used for this concept before the port, so a call
    /// site can be migrated by name instead of by eye. Returns nil when the
    /// symbol has no Lucide counterpart and the call site needs a real decision
    /// — for example a filled status dot, which the web draws as a shape
    /// (`WebStatusDot`) rather than an icon.
    ///
    /// Deliberately unmapped: `circle.fill`.
    static func forSFSymbol(_ systemName: String) -> Lucide? {
        switch systemName {
        case "antenna.radiowaves.left.and.right": return .wifi
        case "archivebox": return .archive
        case "arrow.clockwise": return .refreshCw
        case "arrow.clockwise.circle": return .refreshCw
        case "arrow.down": return .arrowDown
        case "arrow.down.circle": return .circleArrowDown
        case "arrow.down.left": return .arrowDownLeft
        case "arrow.left": return .arrowLeft
        case "arrow.right": return .arrowRight
        case "arrow.right.doc.on.clipboard": return .fileOutput
        case "arrow.right.to.line": return .arrowRightToLine
        case "arrow.triangle.2.circlepath": return .refreshCw
        case "arrow.triangle.branch": return .gitBranch
        case "arrow.triangle.swap": return .arrowLeftRight
        case "arrow.up": return .arrowUp
        case "arrow.up.circle.fill": return .circleArrowUp
        case "arrow.up.left.and.arrow.down.right": return .maximize2
        case "arrow.up.right": return .arrowUpRight
        case "arrow.uturn.backward": return .undo2
        case "bell.badge.fill": return .bellRing
        case "bird.fill": return .bird
        case "bolt.fill": return .zap
        case "bolt.slash": return .zapOff
        case "bolt.slash.fill": return .zapOff
        case "brain": return .brain
        case "bubble.left.and.bubble.right": return .messagesSquare
        case "bubble.left.and.text.bubble.right": return .messagesSquare
        case "bubble.left.and.text.bubble.right.fill": return .messagesSquare
        case "camera": return .camera
        case "checklist": return .listChecks
        case "checkmark": return .check
        case "checkmark.circle": return .circleCheck
        case "checkmark.circle.fill": return .circleCheckBig
        case "checkmark.seal": return .badgeCheck
        case "checkmark.seal.fill": return .badgeCheck
        case "checkmark.square.fill": return .squareCheck
        case "chevron.down": return .chevronDown
        case "chevron.left": return .chevronLeft
        case "chevron.left.forwardslash.chevron.right": return .code
        case "chevron.right": return .chevronRight
        case "chevron.up": return .chevronUp
        case "chevron.up.chevron.down": return .chevronsUpDown
        case "circle": return .circle
        case "circle.dashed": return .circleDashed
        case "circle.dotted.circle": return .circleDotDashed
        case "circle.hexagongrid.fill": return .palette
        case "circle.inset.filled": return .circleDot
        case "clear": return .delete
        case "clock": return .clock
        case "clock.arrow.circlepath": return .history
        case "cloud": return .cloud
        case "cloud.fill": return .cloud
        case "cpu": return .cpu
        case "curlybraces": return .braces
        case "doc": return .file
        case "doc.on.doc": return .copy
        case "doc.plaintext": return .fileText
        case "doc.text": return .fileText
        case "ellipsis": return .ellipsis
        case "ellipsis.circle": return .ellipsis
        case "exclamationmark": return .circleAlert
        case "exclamationmark.circle": return .circleAlert
        case "exclamationmark.circle.fill": return .circleAlert
        case "exclamationmark.shield.fill": return .shieldAlert
        case "exclamationmark.triangle": return .triangleAlert
        case "exclamationmark.triangle.fill": return .triangleAlert
        case "eye": return .eye
        case "eye.slash": return .eyeOff
        case "folder": return .folder
        case "folder.badge.plus": return .folderPlus
        case "folder.badge.questionmark": return .folderSearch
        case "folder.fill": return .folder
        case "gearshape": return .settings
        case "globe": return .globe
        case "graduationcap": return .graduationCap
        case "hourglass": return .hourglass
        case "house": return .house
        case "info.circle": return .info
        case "info.circle.fill": return .info
        case "iphone": return .smartphone
        case "key": return .key
        case "key.fill": return .keyRound
        case "key.slash": return .keyRound
        case "keyboard.chevron.compact.down": return .keyboardOff
        case "largecircle.fill.circle": return .circleDot
        case "list.bullet": return .list
        case "list.bullet.clipboard": return .clipboardList
        case "lock.fill": return .lock
        case "magnifyingglass": return .search
        case "message": return .messageSquare
        case "message.fill": return .messageCircle
        case "minus.circle.fill": return .circleMinus
        case "moon.stars.fill": return .moonStar
        case "moon.zzz": return .moon
        case "network": return .network
        case "number": return .hash
        case "paperplane": return .send
        case "paperplane.fill": return .send
        case "pencil": return .pencil
        case "person.2": return .users
        case "person.crop.circle": return .circleUser
        case "person.crop.circle.fill": return .circleUser
        case "person.fill": return .user
        case "person.fill.questionmark": return .messageCircleQuestionMark
        case "photo": return .image
        case "photo.on.rectangle": return .images
        case "pin": return .pin
        case "pin.slash": return .pinOff
        case "plus": return .plus
        case "plus.bubble": return .messageSquarePlus
        case "plus.circle": return .circlePlus
        case "plus.circle.fill": return .circlePlus
        case "puzzlepiece.extension": return .puzzle
        case "puzzlepiece.extension.fill": return .puzzle
        case "qrcode": return .qrCode
        case "qrcode.viewfinder": return .scanQrCode
        case "questionmark.bubble": return .messageCircleQuestion
        case "questionmark.bubble.fill": return .messageCircleQuestion
        case "server.rack": return .server
        case "shippingbox": return .package
        case "sidebar.left": return .panelLeft
        case "slash.circle": return .circleSlash
        case "slider.horizontal.3": return .slidersHorizontal
        case "sparkles": return .sparkles
        case "square": return .square
        case "square.and.arrow.down": return .download
        case "square.and.pencil": return .squarePen
        case "square.stack.3d.up.fill": return .layers
        case "star": return .star
        case "stop.fill": return .square
        case "sun.max.fill": return .sun
        case "terminal": return .terminal
        case "text.bubble": return .messageSquareText
        case "trash": return .trash2
        case "tray": return .inbox
        case "video.slash": return .videoOff
        case "wand.and.stars": return .wandSparkles
        case "wand.and.stars.inverse": return .wandSparkles
        case "waveform": return .activity
        case "wrench.and.screwdriver": return .wrench
        case "xmark": return .x
        case "xmark.circle": return .circleX
        case "xmark.circle.fill": return .circleX
        case "xmark.octagon.fill": return .octagonX
        default: return nil
        }
    }
}
