// Generated by scripts/gen-web-tokens.mjs — DO NOT EDIT BY HAND.
//
// The Tailwind ramp colors the web client uses directly, rather than through a
// theme token: conversation status dots and the 16 folder identity colors. They
// are deliberately *not* theme-driven — a folder keeps its color and a status
// keeps its meaning under every preset, on the web and here.

import SwiftUI

enum WebPalette {
    /// Tailwind `red-500`
    static let red500 = Color(.sRGB, red: 0.98266, green: 0.17180, blue: 0.21307, opacity: 1) // #FB2C36
    /// Tailwind `orange-500`
    static let orange500 = Color(.sRGB, red: 1.0, green: 0.41082, blue: 0.0, opacity: 1) // #FF6900
    /// Tailwind `amber-500`
    static let amber500 = Color(.sRGB, red: 0.99196, green: 0.60343, blue: 0.0, opacity: 1) // #FD9A00
    /// Tailwind `yellow-400`
    static let yellow400 = Color(.sRGB, red: 0.98745, green: 0.78367, blue: 0.0, opacity: 1) // #FCC800
    /// Tailwind `yellow-500`
    static let yellow500 = Color(.sRGB, red: 0.93853, green: 0.69398, blue: 0.0, opacity: 1) // #EFB100
    /// Tailwind `lime-500`
    static let lime500 = Color(.sRGB, red: 0.48735, green: 0.80990, blue: 0.0, opacity: 1) // #7CCF00
    /// Tailwind `green-500`
    static let green500 = Color(.sRGB, red: 0.0, green: 0.78713, blue: 0.31574, opacity: 1) // #00C951
    /// Tailwind `emerald-500`
    static let emerald500 = Color(.sRGB, red: 0.0, green: 0.73874, blue: 0.48935, opacity: 1) // #00BC7D
    /// Tailwind `teal-500`
    static let teal500 = Color(.sRGB, red: 0.0, green: 0.73331, blue: 0.65486, opacity: 1) // #00BBA7
    /// Tailwind `cyan-500`
    static let cyan500 = Color(.sRGB, red: 0.0, green: 0.72184, blue: 0.85723, opacity: 1) // #00B8DB
    /// Tailwind `sky-500`
    static let sky500 = Color(.sRGB, red: 0.0, green: 0.64976, blue: 0.95696, opacity: 1) // #00A6F4
    /// Tailwind `blue-500`
    static let blue500 = Color(.sRGB, red: 0.16947, green: 0.49808, blue: 1.0, opacity: 1) // #2B7FFF
    /// Tailwind `indigo-500`
    static let indigo500 = Color(.sRGB, red: 0.38218, green: 0.37195, blue: 1.0, opacity: 1) // #615FFF
    /// Tailwind `violet-500`
    static let violet500 = Color(.sRGB, red: 0.55590, green: 0.31826, blue: 1.0, opacity: 1) // #8E51FF
    /// Tailwind `purple-500`
    static let purple500 = Color(.sRGB, red: 0.67787, green: 0.27608, blue: 1.0, opacity: 1) // #AD46FF
    /// Tailwind `fuchsia-500`
    static let fuchsia500 = Color(.sRGB, red: 0.88369, green: 0.16575, blue: 0.98450, opacity: 1) // #E12AFB
    /// Tailwind `pink-500`
    static let pink500 = Color(.sRGB, red: 0.96581, green: 0.19814, blue: 0.60432, opacity: 1) // #F6339A
    /// Tailwind `gray-400`
    static let gray400 = Color(.sRGB, red: 0.60001, green: 0.63140, blue: 0.68522, opacity: 1) // #99A1AF
    /// Tailwind `gray-500`
    static let gray500 = Color(.sRGB, red: 0.41545, green: 0.44709, blue: 0.51050, opacity: 1) // #6A7282
}

/// `STATUS_COLORS` from src/lib/types.ts. The web uses one value per status in
/// both color schemes, so these carry no light/dark pair.
enum WebStatusPalette {
    /// `bg-yellow-400`
    static let inProgress = WebPalette.yellow400
    /// `bg-blue-500`
    static let pendingReview = WebPalette.blue500
    /// `bg-green-500`
    static let completed = WebPalette.green500
    /// `bg-red-500`
    static let cancelled = WebPalette.red500
    /// The web's fallback for an unknown status (`bg-gray-400 dark:bg-gray-500`).
    static let unknown = Color(light: WebPalette.gray400, dark: WebPalette.gray500)
}

/// `folderBadgeColor` / `folderBadgeLabel` from src/lib/folder-badge.ts: a
/// folder's identity color is its id modulo the ramp, so the same folder gets
/// the same color in both clients.
enum WebFolderPalette {
    static let colors: [Color] = [
        WebPalette.red500, // red-500
        WebPalette.orange500, // orange-500
        WebPalette.amber500, // amber-500
        WebPalette.yellow500, // yellow-500
        WebPalette.lime500, // lime-500
        WebPalette.green500, // green-500
        WebPalette.emerald500, // emerald-500
        WebPalette.teal500, // teal-500
        WebPalette.cyan500, // cyan-500
        WebPalette.sky500, // sky-500
        WebPalette.blue500, // blue-500
        WebPalette.indigo500, // indigo-500
        WebPalette.violet500, // violet-500
        WebPalette.purple500, // purple-500
        WebPalette.fuchsia500, // fuchsia-500
        WebPalette.pink500, // pink-500
    ]

    static func color(forFolderID id: Int) -> Color {
        colors[abs(id) % colors.count]
    }

    /// The badge's single-character label: the name's first letter or digit,
    /// uppercased; `?` when there is neither.
    static func label(for name: String) -> String {
        for character in name {
            if character.isLetter || character.isNumber {
                return character.uppercased()
            }
        }
        return name.isEmpty ? "?" : String(name.prefix(1)).uppercased()
    }
}
