// Generated by scripts/gen-web-tokens.mjs — DO NOT EDIT BY HAND.
//
// Source: the web client's src/app/globals.css (31 tokens ×
// 12 presets × light/dark). Oklch values are converted to sRGB with
// the CSS Color 4 gamut-mapping algorithm, so these are the exact colors a
// browser paints for the same theme. Re-run the generator after a web theme
// change rather than editing a value here.

import SwiftUI

/// One resolved token color, in gamma-encoded sRGB.
struct WebRGBA: Equatable, Sendable {
    let r: Double
    let g: Double
    let b: Double
    let a: Double

    init(_ r: Double, _ g: Double, _ b: Double, _ a: Double = 1) {
        self.r = r
        self.g = g
        self.b = b
        self.a = a
    }

    var color: Color { Color(.sRGB, red: r, green: g, blue: b, opacity: a) }
}

/// The web's shadcn color presets, in the web's own picker order
/// (`THEME_COLORS` in src/lib/theme-presets.ts).
enum WebThemeColor: String, CaseIterable, Identifiable, Sendable {
    case neutral = "neutral"
    case zinc = "zinc"
    case slate = "slate"
    case stone = "stone"
    case gray = "gray"
    case red = "red"
    case rose = "rose"
    case orange = "orange"
    case green = "green"
    case blue = "blue"
    case yellow = "yellow"
    case violet = "violet"

    var id: String { rawValue }

    /// The web's default preset — pure grayscale, zero chroma.
    static let `default`: WebThemeColor = .neutral

    /// The swatch shown in the theme picker: this preset's own light `--primary`,
    /// resolved independently of the active theme (mirrors `THEME_COLOR_PREVIEW`).
    var swatch: Color { WebTokens.value(.primary, theme: self, dark: false).color }
}

/// Every CSS custom property the web theme blocks define.
enum WebToken: String, CaseIterable, Sendable {
    case background = "background"
    case foreground = "foreground"
    case card = "card"
    case cardForeground = "card-foreground"
    case popover = "popover"
    case popoverForeground = "popover-foreground"
    case primary = "primary"
    case primaryForeground = "primary-foreground"
    case secondary = "secondary"
    case secondaryForeground = "secondary-foreground"
    case muted = "muted"
    case mutedForeground = "muted-foreground"
    case accent = "accent"
    case accentForeground = "accent-foreground"
    case destructive = "destructive"
    case border = "border"
    case input = "input"
    case ring = "ring"
    case chart1 = "chart-1"
    case chart2 = "chart-2"
    case chart3 = "chart-3"
    case chart4 = "chart-4"
    case chart5 = "chart-5"
    case sidebar = "sidebar"
    case sidebarForeground = "sidebar-foreground"
    case sidebarPrimary = "sidebar-primary"
    case sidebarPrimaryForeground = "sidebar-primary-foreground"
    case sidebarAccent = "sidebar-accent"
    case sidebarAccentForeground = "sidebar-accent-foreground"
    case sidebarBorder = "sidebar-border"
    case sidebarRing = "sidebar-ring"
}

enum WebTokens {
    /// The token table lookup. A nested switch (rather than a dictionary literal)
    /// keeps this cheap to type-check and free of runtime hashing.
    static func value(_ token: WebToken, theme: WebThemeColor, dark: Bool) -> WebRGBA {
        switch (theme, dark) {
        case (.neutral, false): return neutralLight(token)
        case (.neutral, true): return neutralDark(token)
        case (.zinc, false): return zincLight(token)
        case (.zinc, true): return zincDark(token)
        case (.slate, false): return slateLight(token)
        case (.slate, true): return slateDark(token)
        case (.stone, false): return stoneLight(token)
        case (.stone, true): return stoneDark(token)
        case (.gray, false): return grayLight(token)
        case (.gray, true): return grayDark(token)
        case (.red, false): return redLight(token)
        case (.red, true): return redDark(token)
        case (.rose, false): return roseLight(token)
        case (.rose, true): return roseDark(token)
        case (.orange, false): return orangeLight(token)
        case (.orange, true): return orangeDark(token)
        case (.green, false): return greenLight(token)
        case (.green, true): return greenDark(token)
        case (.blue, false): return blueLight(token)
        case (.blue, true): return blueDark(token)
        case (.yellow, false): return yellowLight(token)
        case (.yellow, true): return yellowDark(token)
        case (.violet, false): return violetLight(token)
        case (.violet, true): return violetDark(token)
        }
    }

    private static func neutralLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .foreground: return WebRGBA(0.03939, 0.03939, 0.03939) // #0A0A0A
        case .card: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .cardForeground: return WebRGBA(0.03939, 0.03939, 0.03939) // #0A0A0A
        case .popover: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .popoverForeground: return WebRGBA(0.03939, 0.03939, 0.03939) // #0A0A0A
        case .primary: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .primaryForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .secondary: return WebRGBA(0.96059, 0.96059, 0.96059) // #F5F5F5
        case .secondaryForeground: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .muted: return WebRGBA(0.96059, 0.96059, 0.96059) // #F5F5F5
        case .mutedForeground: return WebRGBA(0.45152, 0.45152, 0.45152) // #737373
        case .accent: return WebRGBA(0.96059, 0.96059, 0.96059) // #F5F5F5
        case .accentForeground: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .destructive: return WebRGBA(0.87416, 0.13269, 0.14668) // #DF2225
        case .border: return WebRGBA(0.89816, 0.89816, 0.89816) // #E5E5E5
        case .input: return WebRGBA(0.89816, 0.89816, 0.89816) // #E5E5E5
        case .ring: return WebRGBA(0.63016, 0.63016, 0.63016) // #A1A1A1
        case .chart1: return WebRGBA(0.55670, 0.77316, 1.0) // #8EC5FF
        case .chart2: return WebRGBA(0.16947, 0.49808, 1.0) // #2B7FFF
        case .chart3: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        case .chart4: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart5: return WebRGBA(0.09978, 0.23377, 0.72292) // #193CB8
        case .sidebar: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarForeground: return WebRGBA(0.03939, 0.03939, 0.03939) // #0A0A0A
        case .sidebarPrimary: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .sidebarPrimaryForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarAccent: return WebRGBA(0.92148, 0.92148, 0.92148) // #EBEBEB
        case .sidebarAccentForeground: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .sidebarBorder: return WebRGBA(0.89816, 0.89816, 0.89816) // #E5E5E5
        case .sidebarRing: return WebRGBA(0.63016, 0.63016, 0.63016) // #A1A1A1
        }
    }

    private static func neutralDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.03939, 0.03939, 0.03939) // #0A0A0A
        case .foreground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .card: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .cardForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .popover: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .popoverForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .primary: return WebRGBA(0.83144, 0.83144, 0.83144) // #D4D4D4
        case .primaryForeground: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .secondary: return WebRGBA(0.14938, 0.14938, 0.14938) // #262626
        case .secondaryForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .muted: return WebRGBA(0.14938, 0.14938, 0.14938) // #262626
        case .mutedForeground: return WebRGBA(0.63016, 0.63016, 0.63016) // #A1A1A1
        case .accent: return WebRGBA(0.25047, 0.25047, 0.25047) // #404040
        case .accentForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.45152, 0.45152, 0.45152) // #737373
        case .chart1: return WebRGBA(0.55670, 0.77316, 1.0) // #8EC5FF
        case .chart2: return WebRGBA(0.16947, 0.49808, 1.0) // #2B7FFF
        case .chart3: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        case .chart4: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart5: return WebRGBA(0.09978, 0.23377, 0.72292) // #193CB8
        case .sidebar: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .sidebarForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarPrimary: return WebRGBA(0.83144, 0.83144, 0.83144) // #D4D4D4
        case .sidebarPrimaryForeground: return WebRGBA(0.09053, 0.09053, 0.09053) // #171717
        case .sidebarAccent: return WebRGBA(0.15988, 0.15988, 0.15988) // #292929
        case .sidebarAccentForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.45152, 0.45152, 0.45152) // #737373
        }
    }

    private static func zincLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .foreground: return WebRGBA(0.03537, 0.03536, 0.04432) // #09090B
        case .card: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .cardForeground: return WebRGBA(0.03537, 0.03536, 0.04432) // #09090B
        case .popover: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .popoverForeground: return WebRGBA(0.03537, 0.03536, 0.04432) // #09090B
        case .primary: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .primaryForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .secondary: return WebRGBA(0.95638, 0.95639, 0.95934) // #F4F4F5
        case .secondaryForeground: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .muted: return WebRGBA(0.95638, 0.95639, 0.95934) // #F4F4F5
        case .mutedForeground: return WebRGBA(0.4430, 0.44293, 0.48380) // #71717B
        case .accent: return WebRGBA(0.95638, 0.95639, 0.95934) // #F4F4F5
        case .accentForeground: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.89448, 0.89448, 0.90615) // #E4E4E7
        case .input: return WebRGBA(0.89448, 0.89448, 0.90615) // #E4E4E7
        case .ring: return WebRGBA(0.62261, 0.62256, 0.66336) // #9F9FA9
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarForeground: return WebRGBA(0.03537, 0.03536, 0.04432) // #09090B
        case .sidebarPrimary: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .sidebarPrimaryForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarAccent: return WebRGBA(0.95638, 0.95639, 0.95934) // #F4F4F5
        case .sidebarAccentForeground: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .sidebarBorder: return WebRGBA(0.89448, 0.89448, 0.90615) // #E4E4E7
        case .sidebarRing: return WebRGBA(0.62261, 0.62256, 0.66336) // #9F9FA9
        }
    }

    private static func zincDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.03537, 0.03536, 0.04432) // #09090B
        case .foreground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .card: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .cardForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .popover: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .popoverForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .primary: return WebRGBA(0.89448, 0.89448, 0.90615) // #E4E4E7
        case .primaryForeground: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .secondary: return WebRGBA(0.15290, 0.15289, 0.16577) // #27272A
        case .secondaryForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .muted: return WebRGBA(0.15290, 0.15289, 0.16577) // #27272A
        case .mutedForeground: return WebRGBA(0.62261, 0.62256, 0.66336) // #9F9FA9
        case .accent: return WebRGBA(0.15290, 0.15289, 0.16577) // #27272A
        case .accentForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.4430, 0.44293, 0.48380) // #71717B
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .sidebarForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarPrimary: return WebRGBA(0.89448, 0.89448, 0.90615) // #E4E4E7
        case .sidebarPrimaryForeground: return WebRGBA(0.09380, 0.09379, 0.10583) // #18181B
        case .sidebarAccent: return WebRGBA(0.15290, 0.15289, 0.16577) // #27272A
        case .sidebarAccentForeground: return WebRGBA(0.98026, 0.98026, 0.98026) // #FAFAFA
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.4430, 0.44293, 0.48380) // #71717B
        }
    }

    private static func slateLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .foreground: return WebRGBA(0.00743, 0.02328, 0.09251) // #020618
        case .card: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .cardForeground: return WebRGBA(0.00743, 0.02328, 0.09251) // #020618
        case .popover: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .popoverForeground: return WebRGBA(0.00743, 0.02328, 0.09251) // #020618
        case .primary: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .primaryForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .secondary: return WebRGBA(0.94447, 0.96050, 0.97652) // #F1F5F9
        case .secondaryForeground: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .muted: return WebRGBA(0.94447, 0.96050, 0.97652) // #F1F5F9
        case .mutedForeground: return WebRGBA(0.38391, 0.45479, 0.55666) // #62748E
        case .accent: return WebRGBA(0.94447, 0.96050, 0.97652) // #F1F5F9
        case .accentForeground: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.88595, 0.91020, 0.94252) // #E2E8F0
        case .input: return WebRGBA(0.88595, 0.91020, 0.94252) // #E2E8F0
        case .ring: return WebRGBA(0.56485, 0.63170, 0.72524) // #90A1B9
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .sidebarForeground: return WebRGBA(0.00743, 0.02328, 0.09251) // #020618
        case .sidebarPrimary: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .sidebarPrimaryForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .sidebarAccent: return WebRGBA(0.94447, 0.96050, 0.97652) // #F1F5F9
        case .sidebarAccentForeground: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .sidebarBorder: return WebRGBA(0.88595, 0.91020, 0.94252) // #E2E8F0
        case .sidebarRing: return WebRGBA(0.56485, 0.63170, 0.72524) // #90A1B9
        }
    }

    private static func slateDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.00743, 0.02328, 0.09251) // #020618
        case .foreground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .card: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .cardForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .popover: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .popoverForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .primary: return WebRGBA(0.88595, 0.91020, 0.94252) // #E2E8F0
        case .primaryForeground: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .secondary: return WebRGBA(0.11213, 0.16004, 0.23867) // #1D293D
        case .secondaryForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .muted: return WebRGBA(0.11213, 0.16004, 0.23867) // #1D293D
        case .mutedForeground: return WebRGBA(0.56485, 0.63170, 0.72524) // #90A1B9
        case .accent: return WebRGBA(0.11213, 0.16004, 0.23867) // #1D293D
        case .accentForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.41545, 0.44709, 0.51050) // #6A7282
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .sidebarForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .sidebarPrimary: return WebRGBA(0.88595, 0.91020, 0.94252) // #E2E8F0
        case .sidebarPrimaryForeground: return WebRGBA(0.05718, 0.09004, 0.16880) // #0F172B
        case .sidebarAccent: return WebRGBA(0.11213, 0.16004, 0.23867) // #1D293D
        case .sidebarAccentForeground: return WebRGBA(0.97315, 0.98004, 0.98694) // #F8FAFC
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.41545, 0.44709, 0.51050) // #6A7282
        }
    }

    private static func stoneLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .foreground: return WebRGBA(0.04696, 0.03936, 0.03554) // #0C0A09
        case .card: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .cardForeground: return WebRGBA(0.04696, 0.03936, 0.03554) // #0C0A09
        case .popover: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .popoverForeground: return WebRGBA(0.04696, 0.03936, 0.03554) // #0C0A09
        case .primary: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .primaryForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .secondary: return WebRGBA(0.96086, 0.96086, 0.95790) // #F5F5F4
        case .secondaryForeground: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .muted: return WebRGBA(0.96086, 0.96086, 0.95790) // #F5F5F4
        case .mutedForeground: return WebRGBA(0.47271, 0.4420, 0.42004) // #79716B
        case .accent: return WebRGBA(0.96086, 0.96086, 0.95790) // #F5F5F4
        case .accentForeground: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.90671, 0.89753, 0.89294) // #E7E5E4
        case .input: return WebRGBA(0.90671, 0.89753, 0.89294) // #E7E5E4
        case .ring: return WebRGBA(0.65213, 0.62622, 0.60894) // #A6A09B
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .sidebarForeground: return WebRGBA(0.04696, 0.03936, 0.03554) // #0C0A09
        case .sidebarPrimary: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .sidebarPrimaryForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .sidebarAccent: return WebRGBA(0.96086, 0.96086, 0.95790) // #F5F5F4
        case .sidebarAccentForeground: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .sidebarBorder: return WebRGBA(0.90671, 0.89753, 0.89294) // #E7E5E4
        case .sidebarRing: return WebRGBA(0.65213, 0.62622, 0.60894) // #A6A09B
        }
    }

    private static func stoneDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.04696, 0.03936, 0.03554) // #0C0A09
        case .foreground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .card: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .cardForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .popover: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .popoverForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .primary: return WebRGBA(0.90671, 0.89753, 0.89294) // #E7E5E4
        case .primaryForeground: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .secondary: return WebRGBA(0.16162, 0.14419, 0.13984) // #292524
        case .secondaryForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .muted: return WebRGBA(0.16162, 0.14419, 0.13984) // #292524
        case .mutedForeground: return WebRGBA(0.65213, 0.62622, 0.60894) // #A6A09B
        case .accent: return WebRGBA(0.16162, 0.14419, 0.13984) // #292524
        case .accentForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.47271, 0.4420, 0.42004) // #79716B
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .sidebarForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .sidebarPrimary: return WebRGBA(0.90671, 0.89753, 0.89294) // #E7E5E4
        case .sidebarPrimaryForeground: return WebRGBA(0.10951, 0.09799, 0.09031) // #1C1917
        case .sidebarAccent: return WebRGBA(0.16162, 0.14419, 0.13984) // #292524
        case .sidebarAccentForeground: return WebRGBA(0.98053, 0.98053, 0.97756) // #FAFAF9
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.47271, 0.4420, 0.42004) // #79716B
        }
    }

    private static func grayLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .foreground: return WebRGBA(0.01158, 0.02761, 0.07188) // #030712
        case .card: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .cardForeground: return WebRGBA(0.01158, 0.02761, 0.07188) // #030712
        case .popover: return WebRGBA(1.0, 1.0, 1.0) // #FFFFFF
        case .popoverForeground: return WebRGBA(0.01158, 0.02761, 0.07188) // #030712
        case .primary: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .primaryForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .secondary: return WebRGBA(0.95284, 0.95693, 0.96512) // #F3F4F6
        case .secondaryForeground: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .muted: return WebRGBA(0.95284, 0.95693, 0.96512) // #F3F4F6
        case .mutedForeground: return WebRGBA(0.41545, 0.44709, 0.51050) // #6A7282
        case .accent: return WebRGBA(0.95284, 0.95693, 0.96512) // #F3F4F6
        case .accentForeground: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.89834, 0.90644, 0.92263) // #E5E7EB
        case .input: return WebRGBA(0.89834, 0.90644, 0.92263) // #E5E7EB
        case .ring: return WebRGBA(0.60001, 0.63140, 0.68522) // #99A1AF
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .sidebarForeground: return WebRGBA(0.01158, 0.02761, 0.07188) // #030712
        case .sidebarPrimary: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .sidebarPrimaryForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .sidebarAccent: return WebRGBA(0.95284, 0.95693, 0.96512) // #F3F4F6
        case .sidebarAccentForeground: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .sidebarBorder: return WebRGBA(0.89834, 0.90644, 0.92263) // #E5E7EB
        case .sidebarRing: return WebRGBA(0.60001, 0.63140, 0.68522) // #99A1AF
        }
    }

    private static func grayDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.01158, 0.02761, 0.07188) // #030712
        case .foreground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .card: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .cardForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .popover: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .popoverForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .primary: return WebRGBA(0.89834, 0.90644, 0.92263) // #E5E7EB
        case .primaryForeground: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .secondary: return WebRGBA(0.11697, 0.16075, 0.22202) // #1E2939
        case .secondaryForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .muted: return WebRGBA(0.11697, 0.16075, 0.22202) // #1E2939
        case .mutedForeground: return WebRGBA(0.60001, 0.63140, 0.68522) // #99A1AF
        case .accent: return WebRGBA(0.11697, 0.16075, 0.22202) // #1E2939
        case .accentForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.41545, 0.44709, 0.51050) // #6A7282
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .sidebarForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .sidebarPrimary: return WebRGBA(0.89834, 0.90644, 0.92263) // #E5E7EB
        case .sidebarPrimaryForeground: return WebRGBA(0.06453, 0.09374, 0.15678) // #101828
        case .sidebarAccent: return WebRGBA(0.11697, 0.16075, 0.22202) // #1E2939
        case .sidebarAccentForeground: return WebRGBA(0.97639, 0.98099, 0.98559) // #F9FAFB
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.41545, 0.44709, 0.51050) // #6A7282
        }
    }

    private static func redLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 0.98858, 0.98692) // #FFFCFC
        case .foreground: return WebRGBA(0.05732, 0.02855, 0.02617) // #0F0707
        case .card: return WebRGBA(1.0, 0.98858, 0.98692) // #FFFCFC
        case .cardForeground: return WebRGBA(0.05732, 0.02855, 0.02617) // #0F0707
        case .popover: return WebRGBA(1.0, 0.98858, 0.98692) // #FFFCFC
        case .popoverForeground: return WebRGBA(0.05732, 0.02855, 0.02617) // #0F0707
        case .primary: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        case .primaryForeground: return WebRGBA(0.99684, 0.94959, 0.94959) // #FEF2F2
        case .secondary: return WebRGBA(0.99165, 0.9450, 0.93966) // #FDF1F0
        case .secondaryForeground: return WebRGBA(0.12231, 0.08443, 0.08049) // #1F1615
        case .muted: return WebRGBA(0.99165, 0.9450, 0.93966) // #FDF1F0
        case .mutedForeground: return WebRGBA(0.51792, 0.42069, 0.41023) // #846B69
        case .accent: return WebRGBA(0.99929, 0.92111, 0.91226) // #FFEBE9
        case .accentForeground: return WebRGBA(0.12231, 0.08443, 0.08049) // #1F1615
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.93521, 0.87180, 0.86460) // #EEDEDC
        case .input: return WebRGBA(0.93521, 0.87180, 0.86460) // #EEDEDC
        case .ring: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.99935, 0.97399, 0.97107) // #FFF8F8
        case .sidebarForeground: return WebRGBA(0.05732, 0.02855, 0.02617) // #0F0707
        case .sidebarPrimary: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        case .sidebarPrimaryForeground: return WebRGBA(0.99684, 0.94959, 0.94959) // #FEF2F2
        case .sidebarAccent: return WebRGBA(0.99929, 0.92111, 0.91226) // #FFEBE9
        case .sidebarAccentForeground: return WebRGBA(0.12231, 0.08443, 0.08049) // #1F1615
        case .sidebarBorder: return WebRGBA(0.93521, 0.87180, 0.86460) // #EEDEDC
        case .sidebarRing: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        }
    }

    private static func redDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.05454, 0.02969, 0.02752) // #0E0807
        case .foreground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .card: return WebRGBA(0.11449, 0.08144, 0.07795) // #1D1514
        case .cardForeground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .popover: return WebRGBA(0.11449, 0.08144, 0.07795) // #1D1514
        case .popoverForeground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .primary: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        case .primaryForeground: return WebRGBA(0.99684, 0.94959, 0.94959) // #FEF2F2
        case .secondary: return WebRGBA(0.18391, 0.14311, 0.13872) // #2F2423
        case .secondaryForeground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .muted: return WebRGBA(0.18391, 0.14311, 0.13872) // #2F2423
        case .mutedForeground: return WebRGBA(0.69850, 0.60082, 0.59006) // #B29996
        case .accent: return WebRGBA(0.23742, 0.18450, 0.17886) // #3D2F2E
        case .accentForeground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.11449, 0.08144, 0.07795) // #1D1514
        case .sidebarForeground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .sidebarPrimary: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        case .sidebarPrimaryForeground: return WebRGBA(0.99684, 0.94959, 0.94959) // #FEF2F2
        case .sidebarAccent: return WebRGBA(0.18391, 0.14311, 0.13872) // #2F2423
        case .sidebarAccentForeground: return WebRGBA(0.98848, 0.97758, 0.97632) // #FCF9F9
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.98266, 0.17180, 0.21307) // #FB2C36
        }
    }

    private static func roseLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 0.98836, 0.98852) // #FFFCFC
        case .foreground: return WebRGBA(0.05719, 0.02818, 0.02914) // #0F0707
        case .card: return WebRGBA(1.0, 0.98836, 0.98852) // #FFFCFC
        case .cardForeground: return WebRGBA(0.05719, 0.02818, 0.02914) // #0F0707
        case .popover: return WebRGBA(1.0, 0.98836, 0.98852) // #FFFCFC
        case .popoverForeground: return WebRGBA(0.05719, 0.02818, 0.02914) // #0F0707
        case .primary: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .primaryForeground: return WebRGBA(0.99902, 0.94473, 0.94860) // #FFF1F2
        case .secondary: return WebRGBA(0.99152, 0.94430, 0.94494) // #FDF1F1
        case .secondaryForeground: return WebRGBA(0.12216, 0.08386, 0.08505) // #1F1516
        case .muted: return WebRGBA(0.99152, 0.94430, 0.94494) // #FDF1F1
        case .mutedForeground: return WebRGBA(0.51757, 0.41923, 0.42174) // #846B6C
        case .accent: return WebRGBA(0.99905, 0.91993, 0.92119) // #FFEBEB
        case .accentForeground: return WebRGBA(0.12216, 0.08386, 0.08505) // #1F1516
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.93502, 0.87085, 0.87182) // #EEDEDE
        case .input: return WebRGBA(0.93502, 0.87085, 0.87182) // #EEDEDE
        case .ring: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.99928, 0.97361, 0.97392) // #FFF8F8
        case .sidebarForeground: return WebRGBA(0.05719, 0.02818, 0.02914) // #0F0707
        case .sidebarPrimary: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebarPrimaryForeground: return WebRGBA(0.99902, 0.94473, 0.94860) // #FFF1F2
        case .sidebarAccent: return WebRGBA(0.99905, 0.91993, 0.92119) // #FFEBEB
        case .sidebarAccentForeground: return WebRGBA(0.12216, 0.08386, 0.08505) // #1F1516
        case .sidebarBorder: return WebRGBA(0.93502, 0.87085, 0.87182) // #EEDEDE
        case .sidebarRing: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        }
    }

    private static func roseDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.05444, 0.02937, 0.03011) // #0E0708
        case .foreground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .card: return WebRGBA(0.11437, 0.08094, 0.08190) // #1D1515
        case .cardForeground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .popover: return WebRGBA(0.11437, 0.08094, 0.08190) // #1D1515
        case .popoverForeground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .primary: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .primaryForeground: return WebRGBA(0.99902, 0.94473, 0.94860) // #FFF1F2
        case .secondary: return WebRGBA(0.18376, 0.14250, 0.14356) // #2F2425
        case .secondaryForeground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .muted: return WebRGBA(0.18376, 0.14250, 0.14356) // #2F2425
        case .mutedForeground: return WebRGBA(0.69816, 0.59936, 0.60145) // #B29999
        case .accent: return WebRGBA(0.23723, 0.18371, 0.18515) // #3C2F2F
        case .accentForeground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.11437, 0.08094, 0.08190) // #1D1515
        case .sidebarForeground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .sidebarPrimary: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebarPrimaryForeground: return WebRGBA(0.99902, 0.94473, 0.94860) // #FFF1F2
        case .sidebarAccent: return WebRGBA(0.18376, 0.14250, 0.14356) // #2F2425
        case .sidebarAccentForeground: return WebRGBA(0.98845, 0.97742, 0.97754) // #FCF9F9
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        }
    }

    private static func orangeLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(1.0, 0.98947, 0.98352) // #FFFCFB
        case .foreground: return WebRGBA(0.05566, 0.03021, 0.02022) // #0E0805
        case .card: return WebRGBA(1.0, 0.98947, 0.98352) // #FFFCFB
        case .cardForeground: return WebRGBA(0.05566, 0.03021, 0.02022) // #0E0805
        case .popover: return WebRGBA(1.0, 0.98947, 0.98352) // #FFFCFB
        case .popoverForeground: return WebRGBA(0.05566, 0.03021, 0.02022) // #0E0805
        case .primary: return WebRGBA(1.0, 0.41082, 0.0) // #FF6900
        case .primaryForeground: return WebRGBA(1.0, 0.96907, 0.92944) // #FFF7ED
        case .secondary: return WebRGBA(0.98841, 0.94792, 0.92846) // #FCF2ED
        case .secondaryForeground: return WebRGBA(0.12008, 0.08689, 0.07053) // #1F1612
        case .muted: return WebRGBA(0.98841, 0.94792, 0.92846) // #FCF2ED
        case .mutedForeground: return WebRGBA(0.51193, 0.42695, 0.38534) // #836D62
        case .accent: return WebRGBA(0.99401, 0.92603, 0.89321) // #FDECE4
        case .accentForeground: return WebRGBA(0.12008, 0.08689, 0.07053) // #1F1612
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.93089, 0.87578, 0.84922) // #EDDFD9
        case .input: return WebRGBA(0.93089, 0.87578, 0.84922) // #EDDFD9
        case .ring: return WebRGBA(1.0, 0.41082, 0.0) // #FF6900
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.99755, 0.97557, 0.96504) // #FEF9F6
        case .sidebarForeground: return WebRGBA(0.05566, 0.03021, 0.02022) // #0E0805
        case .sidebarPrimary: return WebRGBA(1.0, 0.41082, 0.0) // #FF6900
        case .sidebarPrimaryForeground: return WebRGBA(1.0, 0.96907, 0.92944) // #FFF7ED
        case .sidebarAccent: return WebRGBA(0.99401, 0.92603, 0.89321) // #FDECE4
        case .sidebarAccentForeground: return WebRGBA(0.12008, 0.08689, 0.07053) // #1F1612
        case .sidebarBorder: return WebRGBA(0.93089, 0.87578, 0.84922) // #EDDFD9
        case .sidebarRing: return WebRGBA(1.0, 0.41082, 0.0) // #FF6900
        }
    }

    private static func orangeDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.05307, 0.03114, 0.02229) // #0E0806
        case .foreground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .card: return WebRGBA(0.11251, 0.08358, 0.06936) // #1D1512
        case .cardForeground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .popover: return WebRGBA(0.11251, 0.08358, 0.06936) // #1D1512
        case .popoverForeground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .primary: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .primaryForeground: return WebRGBA(1.0, 0.96907, 0.92944) // #FFF7ED
        case .secondary: return WebRGBA(0.18140, 0.14573, 0.12827) // #2E2521
        case .secondaryForeground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .muted: return WebRGBA(0.18140, 0.14573, 0.12827) // #2E2521
        case .mutedForeground: return WebRGBA(0.69223, 0.60705, 0.56560) // #B19B90
        case .accent: return WebRGBA(0.23420, 0.18792, 0.16523) // #3C302A
        case .accentForeground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.11251, 0.08358, 0.06936) // #1D1512
        case .sidebarForeground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .sidebarPrimary: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .sidebarPrimaryForeground: return WebRGBA(1.0, 0.96907, 0.92944) // #FFF7ED
        case .sidebarAccent: return WebRGBA(0.18140, 0.14573, 0.12827) // #2E2521
        case .sidebarAccentForeground: return WebRGBA(0.98770, 0.97826, 0.97374) // #FCF9F8
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        }
    }

    private static func greenLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.98535, 0.99548, 0.98669) // #FBFEFC
        case .foreground: return WebRGBA(0.02276, 0.04291, 0.02575) // #060B07
        case .card: return WebRGBA(0.98535, 0.99548, 0.98669) // #FBFEFC
        case .cardForeground: return WebRGBA(0.02276, 0.04291, 0.02575) // #060B07
        case .popover: return WebRGBA(0.98535, 0.99548, 0.98669) // #FBFEFC
        case .popoverForeground: return WebRGBA(0.02276, 0.04291, 0.02575) // #060B07
        case .primary: return WebRGBA(0.0, 0.78713, 0.31574) // #00C951
        case .primaryForeground: return WebRGBA(0.94139, 0.99220, 0.95702) // #F0FDF4
        case .secondary: return WebRGBA(0.93472, 0.96751, 0.93915) // #EEF7EF
        case .secondaryForeground: return WebRGBA(0.07530, 0.10365, 0.07989) // #131A14
        case .muted: return WebRGBA(0.93472, 0.96751, 0.93915) // #EEF7EF
        case .mutedForeground: return WebRGBA(0.39786, 0.46936, 0.40885) // #657868
        case .accent: return WebRGBA(0.90363, 0.95915, 0.91135) // #E6F5E8
        case .accentForeground: return WebRGBA(0.07530, 0.10365, 0.07989) // #131A14
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.85770, 0.90256, 0.86387) // #DBE6DC
        case .input: return WebRGBA(0.85770, 0.90256, 0.86387) // #DBE6DC
        case .ring: return WebRGBA(0.0, 0.78713, 0.31574) // #00C951
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.96845, 0.98615, 0.97080) // #F7FBF8
        case .sidebarForeground: return WebRGBA(0.02276, 0.04291, 0.02575) // #060B07
        case .sidebarPrimary: return WebRGBA(0.0, 0.78713, 0.31574) // #00C951
        case .sidebarPrimaryForeground: return WebRGBA(0.94139, 0.99220, 0.95702) // #F0FDF4
        case .sidebarAccent: return WebRGBA(0.90363, 0.95915, 0.91135) // #E6F5E8
        case .sidebarAccentForeground: return WebRGBA(0.07530, 0.10365, 0.07989) // #131A14
        case .sidebarBorder: return WebRGBA(0.85770, 0.90256, 0.86387) // #DBE6DC
        case .sidebarRing: return WebRGBA(0.0, 0.78713, 0.31574) // #00C951
        }
    }

    private static func greenDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.02465, 0.0420, 0.02717) // #060B07
        case .foreground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .card: return WebRGBA(0.07356, 0.09812, 0.07745) // #131914
        case .cardForeground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .popover: return WebRGBA(0.07356, 0.09812, 0.07745) // #131914
        case .popoverForeground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .primary: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .primaryForeground: return WebRGBA(0.05113, 0.32869, 0.17017) // #0D542B
        case .secondary: return WebRGBA(0.13352, 0.16354, 0.13814) // #222A23
        case .secondaryForeground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .muted: return WebRGBA(0.13352, 0.16354, 0.13814) // #222A23
        case .mutedForeground: return WebRGBA(0.57839, 0.64913, 0.58878) // #93A696
        case .accent: return WebRGBA(0.1720, 0.21109, 0.17809) // #2C362D
        case .accentForeground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.07356, 0.09812, 0.07745) // #131914
        case .sidebarForeground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .sidebarPrimary: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .sidebarPrimaryForeground: return WebRGBA(0.05113, 0.32869, 0.17017) // #0D542B
        case .sidebarAccent: return WebRGBA(0.13352, 0.16354, 0.13814) // #222A23
        case .sidebarAccentForeground: return WebRGBA(0.97522, 0.98279, 0.97621) // #F9FBF9
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        }
    }

    private static func blueLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.98676, 0.99256, 1.0) // #FCFDFF
        case .foreground: return WebRGBA(0.02584, 0.03650, 0.05953) // #07090F
        case .card: return WebRGBA(0.98676, 0.99256, 1.0) // #FCFDFF
        case .cardForeground: return WebRGBA(0.02584, 0.03650, 0.05953) // #07090F
        case .popover: return WebRGBA(0.98676, 0.99256, 1.0) // #FCFDFF
        case .popoverForeground: return WebRGBA(0.02584, 0.03650, 0.05953) // #07090F
        case .primary: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        case .primaryForeground: return WebRGBA(0.93694, 0.96403, 0.99887) // #EFF6FF
        case .secondary: return WebRGBA(0.93913, 0.95808, 0.99303) // #EFF4FD
        case .secondaryForeground: return WebRGBA(0.07998, 0.09557, 0.12472) // #141820
        case .muted: return WebRGBA(0.93913, 0.95808, 0.99303) // #EFF4FD
        case .mutedForeground: return WebRGBA(0.40899, 0.44893, 0.52323) // #687285
        case .accent: return WebRGBA(0.91146, 0.94320, 1.0) // #E8F1FF
        case .accentForeground: return WebRGBA(0.07998, 0.09557, 0.12472) // #141820
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.86386, 0.88968, 0.93732) // #DCE3EF
        case .input: return WebRGBA(0.86386, 0.88968, 0.93732) // #DCE3EF
        case .ring: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.97079, 0.98106, 0.99999) // #F8FAFF
        case .sidebarForeground: return WebRGBA(0.02584, 0.03650, 0.05953) // #07090F
        case .sidebarPrimary: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        case .sidebarPrimaryForeground: return WebRGBA(0.93694, 0.96403, 0.99887) // #EFF6FF
        case .sidebarAccent: return WebRGBA(0.91146, 0.94320, 1.0) // #E8F1FF
        case .sidebarAccentForeground: return WebRGBA(0.07998, 0.09557, 0.12472) // #141820
        case .sidebarBorder: return WebRGBA(0.86386, 0.88968, 0.93732) // #DCE3EF
        case .sidebarRing: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        }
    }

    private static func blueDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.02724, 0.03655, 0.05628) // #07090E
        case .foreground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .card: return WebRGBA(0.07752, 0.09111, 0.11647) // #14171E
        case .cardForeground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .popover: return WebRGBA(0.07752, 0.09111, 0.11647) // #14171E
        case .popoverForeground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .primary: return WebRGBA(0.16947, 0.49808, 1.0) // #2B7FFF
        case .primaryForeground: return WebRGBA(0.93694, 0.96403, 0.99887) // #EFF6FF
        case .secondary: return WebRGBA(0.13820, 0.15496, 0.18614) // #23282F
        case .secondaryForeground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .muted: return WebRGBA(0.13820, 0.15496, 0.18614) // #23282F
        case .mutedForeground: return WebRGBA(0.58885, 0.62887, 0.70302) // #96A0B3
        case .accent: return WebRGBA(0.17818, 0.19993, 0.24043) // #2D333D
        case .accentForeground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.07752, 0.09111, 0.11647) // #14171E
        case .sidebarForeground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .sidebarPrimary: return WebRGBA(0.08362, 0.36442, 0.98634) // #155DFC
        case .sidebarPrimaryForeground: return WebRGBA(0.93694, 0.96403, 0.99887) // #EFF6FF
        case .sidebarAccent: return WebRGBA(0.13820, 0.15496, 0.18614) // #23282F
        case .sidebarAccentForeground: return WebRGBA(0.97620, 0.98061, 0.98873) // #F9FAFC
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        }
    }

    private static func yellowLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.99696, 0.99181, 0.98068) // #FEFDFA
        case .foreground: return WebRGBA(0.04646, 0.03501, 0.01583) // #0C0904
        case .card: return WebRGBA(0.99696, 0.99181, 0.98068) // #FEFDFA
        case .cardForeground: return WebRGBA(0.04646, 0.03501, 0.01583) // #0C0904
        case .popover: return WebRGBA(0.99696, 0.99181, 0.98068) // #FEFDFA
        case .popoverForeground: return WebRGBA(0.04646, 0.03501, 0.01583) // #0C0904
        case .primary: return WebRGBA(0.93853, 0.69398, 0.0) // #EFB100
        case .primaryForeground: return WebRGBA(0.45049, 0.24240, 0.04090) // #733E0A
        case .secondary: return WebRGBA(0.97235, 0.95565, 0.91962) // #F8F4EB
        case .secondaryForeground: return WebRGBA(0.10803, 0.09357, 0.06226) // #1C1810
        case .muted: return WebRGBA(0.97235, 0.95565, 0.91962) // #F8F4EB
        case .mutedForeground: return WebRGBA(0.48031, 0.44379, 0.36507) // #7A715D
        case .accent: return WebRGBA(0.96743, 0.93911, 0.87811) // #F7EFE0
        case .accentForeground: return WebRGBA(0.10803, 0.09357, 0.06226) // #1C1810
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.90924, 0.88636, 0.83706) // #E8E2D5
        case .input: return WebRGBA(0.90924, 0.88636, 0.83706) // #E8E2D5
        case .ring: return WebRGBA(0.93853, 0.69398, 0.0) // #EFB100
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.98875, 0.97974, 0.96029) // #FCFAF5
        case .sidebarForeground: return WebRGBA(0.04646, 0.03501, 0.01583) // #0C0904
        case .sidebarPrimary: return WebRGBA(0.93853, 0.69398, 0.0) // #EFB100
        case .sidebarPrimaryForeground: return WebRGBA(0.45049, 0.24240, 0.04090) // #733E0A
        case .sidebarAccent: return WebRGBA(0.96743, 0.93911, 0.87811) // #F7EFE0
        case .sidebarAccentForeground: return WebRGBA(0.10803, 0.09357, 0.06226) // #1C1810
        case .sidebarBorder: return WebRGBA(0.90924, 0.88636, 0.83706) // #E8E2D5
        case .sidebarRing: return WebRGBA(0.93853, 0.69398, 0.0) // #EFB100
        }
    }

    private static func yellowDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.04501, 0.03526, 0.01839) // #0B0905
        case .foreground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .card: return WebRGBA(0.10190, 0.08936, 0.06229) // #1A1710
        case .cardForeground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .popover: return WebRGBA(0.10190, 0.08936, 0.06229) // #1A1710
        case .popoverForeground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .primary: return WebRGBA(0.93853, 0.69398, 0.0) // #EFB100
        case .primaryForeground: return WebRGBA(0.45049, 0.24240, 0.04090) // #733E0A
        case .secondary: return WebRGBA(0.16814, 0.15280, 0.11976) // #2B271F
        case .secondaryForeground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .muted: return WebRGBA(0.16814, 0.15280, 0.11976) // #2B271F
        case .mutedForeground: return WebRGBA(0.65985, 0.62371, 0.54593) // #A89F8B
        case .accent: return WebRGBA(0.21709, 0.19713, 0.15407) // #373227
        case .accentForeground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.65097, 0.37326, 0.0) // #A65F00
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.10190, 0.08936, 0.06229) // #1A1710
        case .sidebarForeground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .sidebarPrimary: return WebRGBA(0.93853, 0.69398, 0.0) // #EFB100
        case .sidebarPrimaryForeground: return WebRGBA(0.45049, 0.24240, 0.04090) // #733E0A
        case .sidebarAccent: return WebRGBA(0.16814, 0.15280, 0.11976) // #2B271F
        case .sidebarAccentForeground: return WebRGBA(0.98390, 0.98005, 0.97172) // #FBFAF8
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.65097, 0.37326, 0.0) // #A65F00
        }
    }

    private static func violetLight(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.99220, 0.99058, 1.0) // #FDFDFF
        case .foreground: return WebRGBA(0.03678, 0.03259, 0.05744) // #09080F
        case .card: return WebRGBA(0.99220, 0.99058, 1.0) // #FDFDFF
        case .cardForeground: return WebRGBA(0.03678, 0.03259, 0.05744) // #09080F
        case .popover: return WebRGBA(0.99220, 0.99058, 1.0) // #FDFDFF
        case .popoverForeground: return WebRGBA(0.03678, 0.03259, 0.05744) // #09080F
        case .primary: return WebRGBA(0.55590, 0.31826, 1.0) // #8E51FF
        case .primaryForeground: return WebRGBA(0.96059, 0.95278, 0.99966) // #F5F3FF
        case .secondary: return WebRGBA(0.95707, 0.95162, 0.98979) // #F4F3FC
        case .secondaryForeground: return WebRGBA(0.09561, 0.09023, 0.12207) // #18171F
        case .muted: return WebRGBA(0.95707, 0.95162, 0.98979) // #F4F3FC
        case .mutedForeground: return WebRGBA(0.44836, 0.43527, 0.51643) // #726F84
        case .accent: return WebRGBA(0.94177, 0.93234, 0.99662) // #F0EEFE
        case .accentForeground: return WebRGBA(0.09561, 0.09023, 0.12207) // #18171F
        case .destructive: return WebRGBA(0.90637, 0.0, 0.04259) // #E7000B
        case .border: return WebRGBA(0.88844, 0.88088, 0.93292) // #E3E1EE
        case .input: return WebRGBA(0.88844, 0.88088, 0.93292) // #E3E1EE
        case .ring: return WebRGBA(0.55590, 0.31826, 1.0) // #8E51FF
        case .chart1: return WebRGBA(0.96062, 0.28832, 0.0) // #F54A00
        case .chart2: return WebRGBA(0.0, 0.58923, 0.53727) // #009689
        case .chart3: return WebRGBA(0.06373, 0.30671, 0.39374) // #104E64
        case .chart4: return WebRGBA(0.99980, 0.72746, 0.0) // #FFBA00
        case .chart5: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .sidebar: return WebRGBA(0.98046, 0.97756, 0.99824) // #FAF9FF
        case .sidebarForeground: return WebRGBA(0.03678, 0.03259, 0.05744) // #09080F
        case .sidebarPrimary: return WebRGBA(0.55590, 0.31826, 1.0) // #8E51FF
        case .sidebarPrimaryForeground: return WebRGBA(0.96059, 0.95278, 0.99966) // #F5F3FF
        case .sidebarAccent: return WebRGBA(0.94177, 0.93234, 0.99662) // #F0EEFE
        case .sidebarAccentForeground: return WebRGBA(0.09561, 0.09023, 0.12207) // #18171F
        case .sidebarBorder: return WebRGBA(0.88844, 0.88088, 0.93292) // #E3E1EE
        case .sidebarRing: return WebRGBA(0.55590, 0.31826, 1.0) // #8E51FF
        }
    }

    private static func violetDark(_ token: WebToken) -> WebRGBA {
        switch token {
        case .background: return WebRGBA(0.03666, 0.03317, 0.05449) // #09080E
        case .foreground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .card: return WebRGBA(0.09105, 0.08646, 0.11416) // #17161D
        case .cardForeground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .popover: return WebRGBA(0.09105, 0.08646, 0.11416) // #17161D
        case .popoverForeground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .primary: return WebRGBA(0.49991, 0.13370, 0.9960) // #7F22FE
        case .primaryForeground: return WebRGBA(0.96059, 0.95278, 0.99966) // #F5F3FF
        case .secondary: return WebRGBA(0.15473, 0.14923, 0.18329) // #27262F
        case .secondaryForeground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .muted: return WebRGBA(0.15473, 0.14923, 0.18329) // #27262F
        case .mutedForeground: return WebRGBA(0.62774, 0.61520, 0.69622) // #A09DB2
        case .accent: return WebRGBA(0.19971, 0.19248, 0.23673) // #33313C
        case .accentForeground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .destructive: return WebRGBA(1.0, 0.39133, 0.40398) // #FF6467
        case .border: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .input: return WebRGBA(1.0, 1.0, 1.0, 0.150) // #FFFFFF @15%
        case .ring: return WebRGBA(0.49991, 0.13370, 0.9960) // #7F22FE
        case .chart1: return WebRGBA(0.07791, 0.27914, 0.90177) // #1447E6
        case .chart2: return WebRGBA(0.0, 0.73874, 0.48935) // #00BC7D
        case .chart3: return WebRGBA(0.99196, 0.60343, 0.0) // #FD9A00
        case .chart4: return WebRGBA(0.67787, 0.27608, 1.0) // #AD46FF
        case .chart5: return WebRGBA(1.0, 0.12498, 0.33906) // #FF2056
        case .sidebar: return WebRGBA(0.09105, 0.08646, 0.11416) // #17161D
        case .sidebarForeground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .sidebarPrimary: return WebRGBA(0.49991, 0.13370, 0.9960) // #7F22FE
        case .sidebarPrimaryForeground: return WebRGBA(0.96059, 0.95278, 0.99966) // #F5F3FF
        case .sidebarAccent: return WebRGBA(0.15473, 0.14923, 0.18329) // #27262F
        case .sidebarAccentForeground: return WebRGBA(0.98034, 0.97911, 0.98798) // #FAFAFC
        case .sidebarBorder: return WebRGBA(1.0, 1.0, 1.0, 0.10) // #FFFFFF @10%
        case .sidebarRing: return WebRGBA(0.49991, 0.13370, 0.9960) // #7F22FE
        }
    }
}
